### ISSUE TITLE
Why are you checking AppStore Hook with PurchaseToken?

### ISSUE THREAD

**Issue by balkarov** [Geeksltd/Zebble.Billing#1]
Hello!

Thank you for your library!

When user purchases subscription SubscriptionManage saves information about subscription to DB with UserId, TransactionId (OriginalTransactionId) and PurchaseToken.
After when subscription automatically renewed Apple sends notification to server and AppStoreHookInterceptor tries to find subscription in DB with PurchaseToken. But PurchaseToken always new. And AppStoreHookInterceptor saves new record about subscription to DB with same TransactionId. But new subscription have not userId, because AppStoreHookInterceptor cannot find it by PurchaseToken.
 Well... Now I have multiple records with the same TransactionId. 
When I want to know user subscription status SubscriptionManager try find it by UserId. But new subscriptions (from Apple Hook) have <NOT_PROVIDED>. And I always get old Subscription Expired Date.

If user buy this subscriotion again it will get error, because SubscriptionManager tries to find the subscription in DB with TransactionId via SingleOrDefault, but now DB have multiple subscription has the same TransactionId.

I think you understand my problem.
Maybe I don't fully understand something? Maybe AppStoreHookInterceptor must to find (check existing) subscription by OriginalTransactionId? Or maybe AppStoreHookHandler must to find subscription in DB by TransactionId, get UserId from it and save new record to DB with UserId?

I found this [post](https://developer.apple.com/forums/thread/681607?answerId=677534022#677534022) about it.
And user save Subscription to DB  using the OriginalTransactionId as the database primary key. And after when AppStore sends notification they find userId by OriginalTransactionId

**Comment by m-sadegh-sh** [comment]
Hi @balkarov, thanks for your report. Could you please update your Zebble.Billing.* packages and see if your problem is resolved or not?

BTW any pull request is welcome.

**Comment by balkarov** [comment]
@m-sadegh-sh hello.
Thank you for your commit.
But could you explain me why you first search by purchase token and after by transaction id? 
```c#
var subscription = await Repository.GetByPurchaseToken(notification.PurchaseToken);
if (subscription is null)
```

In my tests Apple always sends different PurchaseTokens for the same subscription. And I think you should search purchase by transaction id, isn't it?
```c#
var subscription = await Repository.GetByTransactionId(notification.PurchaseToken);

if (subscription is null)
{
     var subscriptionInfo = await StoreConnector.GetSubscriptionInfo(notification.ToArgs());
     if (subscriptionInfo.Status != SubscriptionQueryStatus.Succeeded) return;

     subscription = await Repository.AddSubscription(new Subscription
...
```

**Comment by m-sadegh-sh** [comment]
@balkarov We need to keep track of all those purchase tokens. That's why we're somehow duplicating those records. This way we have everything on our side and we're able to reprocess everything without needing to call any store-specific endpoint.

**Comment by balkarov** [comment]
@m-sadegh-sh But subscription will be always null in this line
```c#
var subscription = await Repository.GetByPurchaseToken(notification.PurchaseToken);
```

Because Apple always sends different tokens. Or am I wrong?

**Comment by m-sadegh-sh** [comment]
@balkarov You're right, we're getting a new token for every purchase. The actual reason that we first are looking up the record based on purchase token is to cover the scenario in which we receive an exact notification twice or more. A kind of guard to prevent having duplicate records with the same token.
