### ISSUE TITLE
Error parsing AppStore notifications

### ISSUE THREAD

**Issue by mburakeker** [Geeksltd/Zebble.Billing#3]
EnumConverter in AppStoreNotification class is looking for JsonPropertyName attributes in enums:
https://github.com/Geeksltd/Zebble.Billing/blob/d36df30dabbfe8d314472d747c82923f731d850d/Billing.Server.AppStore/Internals/AppStoreNotification.cs#L24
https://github.com/Geeksltd/Zebble.Billing/blob/d36df30dabbfe8d314472d747c82923f731d850d/Billing.Server.AppStore/Json/EnumConverter.cs#L21
But the enums there don't have it, they have EnumMember attributes instead:
https://github.com/Geeksltd/Zebble.Billing/blob/d36df30dabbfe8d314472d747c82923f731d850d/Billing.Server.AppStore/Internals/AppStoreNotificationType.cs#L12
This way it always returns the first member of the enum due to not having a value.

**Comment by m-sadegh-sh** [comment]
@mburakeker Thanks for the bug report. This has been fixed in 2669b0d83f4759ed214e5d31623a12f6f7482570
